version: '3.3'

services:
  vault:
    image: vault
    container_name: vaultserver
    networks:
      - backend
    ports:
      - "8200:8200"
    volumes:
      - ./vault:/vault
    cap_add:
      - IPC_LOCK
    command: ['server']
  oracle:
    image: xrdj6c/oracle-11g-xe
    container_name: oracle
    networks:
      - backend
    ports:
      - "1521:1521"
      - "8081:8080"
    restart: always
    environment:
      ORACLE_ALLOW_REMOTE: "true"
  tomcat:
    image: tomcat:9.0.8-jre8
    container_name: tomcat
    networks:
      - backend
    ports:
      - "8080:8080"
    restart: always
networks:
  backend:
    driver: bridge